import {
  Controller,
  Get,
  Global,
  Inject,
  Injectable,
  Module,
  NotFoundException,
  Param,
  Query,
  Res,
} from '@nestjs/common';
import { createHmac, randomUUID, timingSafeEqual } from 'node:crypto';
import { existsSync } from 'node:fs';
import { mkdir, readFile, unlink } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import type { Response } from 'express';
import { Public } from '../../common/auth.decorators';
import { ENV, type Env } from '../../config/env';

/** `<uuid>.<ext>` — flat, generated by the server, never taken from the uploaded file name. */
const KEY_PATTERN = /^[0-9a-f-]{36}\.[a-z0-9]{2,5}$/;
const URL_TTL_SECONDS = 6 * 3600;

const MIME: Record<string, string> = {
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  png: 'image/png',
  webp: 'image/webp',
  gif: 'image/gif',
  mp4: 'video/mp4',
  m4v: 'video/mp4',
  webm: 'video/webm',
  mov: 'video/quicktime',
};

export const mimeOfKey = (key: string) =>
  MIME[key.split('.').pop() ?? ''] ?? 'application/octet-stream';

/**
 * Uploaded files on local disk (`UPLOAD_DIR`; a Docker volume shared by api and worker).
 * Files are addressed by an opaque key and served through short-lived signed URLs, so
 * `<img>`/`<video>` tags work without the bearer token and links cannot be guessed or reused.
 */
@Injectable()
export class FileStorageService {
  readonly root: string;
  private readonly secret: string;

  constructor(@Inject(ENV) env: Env) {
    this.root = resolve(env.UPLOAD_DIR);
    this.secret = `files:${env.JWT_ACCESS_SECRET}`;
  }

  /** Creates the upload directory (called before the first write). */
  async ensureRoot() {
    await mkdir(this.root, { recursive: true });
    return this.root;
  }

  newKey(ext: string) {
    return `${randomUUID()}.${ext.toLowerCase()}`;
  }

  /** Absolute path of a key; throws on anything that is not a server-generated key. */
  path(key: string) {
    if (!KEY_PATTERN.test(key)) throw new NotFoundException('File not found');
    return join(this.root, key);
  }

  exists(key: string) {
    return KEY_PATTERN.test(key) && existsSync(join(this.root, key));
  }

  async remove(keys: (string | null | undefined)[]) {
    await Promise.all(
      keys
        .filter((k): k is string => !!k && KEY_PATTERN.test(k))
        .map((k) => unlink(join(this.root, k)).catch(() => undefined)),
    );
  }

  /** The file as a `data:` URL (vision input for AI providers). */
  async dataUrl(key: string) {
    const bytes = await readFile(this.path(key));
    return `data:${mimeOfKey(key)};base64,${bytes.toString('base64')}`;
  }

  private sign(key: string, exp: number) {
    return createHmac('sha256', this.secret).update(`${key}:${exp}`).digest('base64url');
  }

  /** Same-origin URL valid for a few hours. */
  signedUrl(key: string | null | undefined): string | null {
    if (!key || !KEY_PATTERN.test(key)) return null;
    const exp = Math.floor(Date.now() / 1000) + URL_TTL_SECONDS;
    return `/api/files/${key}?exp=${exp}&sig=${this.sign(key, exp)}`;
  }

  verify(key: string, exp: string | undefined, sig: string | undefined) {
    const until = Number(exp);
    if (!KEY_PATTERN.test(key) || !sig || !Number.isFinite(until)) return false;
    if (until < Date.now() / 1000) return false;
    const expected = Buffer.from(this.sign(key, until));
    const given = Buffer.from(sig);
    return expected.length === given.length && timingSafeEqual(expected, given);
  }
}

@Controller('files')
export class FilesController {
  constructor(private readonly storage: FileStorageService) {}

  /** Public by design: the signature in the URL is the authorization. Supports Range (video). */
  @Public()
  @Get(':key')
  file(
    @Param('key') key: string,
    @Query('exp') exp: string | undefined,
    @Query('sig') sig: string | undefined,
    @Res() res: Response,
  ) {
    if (!this.storage.verify(key, exp, sig) || !this.storage.exists(key)) {
      throw new NotFoundException('File not found');
    }
    res.setHeader('Content-Type', mimeOfKey(key));
    res.setHeader('Content-Disposition', 'inline');
    res.setHeader('Cache-Control', 'private, max-age=3600');
    res.setHeader('X-Content-Type-Options', 'nosniff');
    res.sendFile(key, { root: this.storage.root, dotfiles: 'deny' });
  }
}

@Global()
@Module({
  controllers: [FilesController],
  providers: [FileStorageService],
  exports: [FileStorageService],
})
export class StorageModule {}
